name: Shantu Daily Check


on:

  workflow_dispatch:

  schedule:

    # 北京时间每天09:00
    # UTC+8

    - cron: "0 1 * * *"



permissions:

  contents: read
  pages: write
  id-token: write



jobs:


  build:


    runs-on: ubuntu-latest


    environment:

      name: github-pages

      url: ${{ steps.deployment.outputs.page_url }}



    steps:



      # 拉取代码

      - name: Checkout

        uses: actions/checkout@v4





      # Python环境

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"





      # Python缓存

      - name: Cache Python packages

        uses: actions/cache@v4

        with:

          path: ~/.cache/pip

          key: python-${{ runner.os }}






      # 安装依赖

      - name: Install requirements

        run: |

          pip install -r shantu/requirements.txt





      # 执行PDF解析

      - name: Run PDF parser

        run: |

          python shantu/scripts/build_index.py






      # 判断是否生成

      - name: Check result

        id: check

        run: |


          if [ -f "shantu/result/status.txt" ]; then


            echo "found=true" >> $GITHUB_OUTPUT


          else


            echo "found=false" >> $GITHUB_OUTPUT


          fi







      # 准备Pages

      - name: Prepare Pages

        if: steps.check.outputs.found == 'true'

        run: |


          mkdir -p public


          cp -r shantu/result/* public/







      # 上传Pages

      - name: Upload Pages artifact

        if: steps.check.outputs.found == 'true'

        uses: actions/upload-pages-artifact@v3

        with:

          path: public






      # 发布Pages

      - name: Deploy to GitHub Pages

        if: steps.check.outputs.found == 'true'

        id: deployment

        uses: actions/deploy-pages@v4







      # PushDeer通知

      - name: PushDeer Notify

        if: steps.check.outputs.found == 'true'

        run: |


          echo "发送PushDeer通知"



          MESSAGE=$(cat shantu/result/notify.txt)



          curl "https://api2.pushdeer.com/message/push" \
          -G \
          --data-urlencode "pushkey=${{ secrets.PUSHDEER_KEY }}" \
          --data-urlencode "text=🌄 山图集更新成功" \
          --data-urlencode "desp=${MESSAGE}"








      # 失败通知

      - name: PushDeer Failed Notify

        if: failure()

        run: |


          curl "https://api2.pushdeer.com/message/push" \
          -G \
          --data-urlencode "pushkey=${{ secrets.PUSHDEER_KEY }}" \
          --data-urlencode "text=❌ 山图集更新失败" \
          --data-urlencode "desp=GitHub Actions执行失败，请检查日志： https://github.com/${{ github.repository }}/actions"
