name: Shantu Daily Check


on:

  workflow_dispatch:


  schedule:

    # 北京时间每天09:00
    # UTC +8
    - cron: "0 1 * * *"



# GitHub Pages权限
permissions:

  contents: read

  pages: write

  id-token: write



jobs:


  build:


    runs-on: ubuntu-latest


    steps:


      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4



      # Python环境
      - name: Setup Python
        uses: actions/setup-python@v5

        with:

          python-version: "3.11"



      # 安装依赖
      - name: Install requirements

        run: |

          pip install -r shantu/requirements.txt



      # 执行PDF解析
      - name: Run PDF parser

        run: |

          python shantu/scripts/build_index.py



      # 判断是否有结果
      - name: Check result

        id: check

        run: |

          if [ -d "shantu/result" ]; then

            echo "has_result=true" >> $GITHUB_OUTPUT

          else

            echo "has_result=false" >> $GITHUB_OUTPUT

          fi



      # 上传Pages文件
      - name: Upload Pages artifact

        if: steps.check.outputs.has_result == 'true'

        uses: actions/upload-pages-artifact@v3

        with:

          path: shantu/result




      # 发布GitHub Pages
      - name: Deploy Pages

        if: steps.check.outputs.has_result == 'true'

        id: deployment

        uses: actions/deploy-pages@v4




      # PushDeer通知
      - name: PushDeer Notify

        if: steps.check.outputs.has_result == 'true'

        run: |


          curl "https://api2.pushdeer.com/message/push" \
          -G \
          --data-urlencode "pushkey=${{ secrets.PUSHDEER_KEY }}" \
          --data-urlencode "text=山图集更新提醒" \
          --data-urlencode "desp=今天的山图集已经生成： https://deanling2011.github.io/shanshitu/"
